###  Get JWT Token
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "wafiyaalim",
  "password": "*********"
}

###  Public Endpoint (No Auth)
GET http://127.0.0.1:8000/api/public/

###  Protected Endpoint (Replace with access token)
GET http://127.0.0.1:8000/api/protected/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODQyNDg0LCJpYXQiOjE3NTA4NDIxODQsImp0aSI6Ijg3YTc2NGViOGQ2ZjQ1YzdhYzg4YzQxZjg0NTUwZjljIiwidXNlcl9pZCI6MX0.A-UXH3pBXCtt_bh9Yuqg236LJq_053opg__hSTnFm-E

###  Protected API
GET http://127.0.0.1:8000/api/telegram-users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODQyNDg0LCJpYXQiOjE3NTA4NDIxODQsImp0aSI6Ijg3YTc2NGViOGQ2ZjQ1YzdhYzg4YzQxZjg0NTUwZjljIiwidXNlcl9pZCI6MX0.A-UXH3pBXCtt_bh9Yuqg236LJq_053opg__hSTnFm-E